# fly.toml app configuration file generated for rough-slack-bot on 2025-05-04T10:31:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rough-slack-bot'
primary_region = 'sin'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '256mb'
  size = 'shared-cpu-1x'

[env]
  PORT = '3000'
  ORIGIN = 'https://slack.rough.app'

# secrets
# -------
# DATABASE_URL=
# ROUGH_CLIENT_ID=
# ROUGH_CLIENT_SECRET=
# SLACK_CLIENT_ID=
# SLACK_CLIENT_SECRET=
# SLACK_SIGNING_SECRET=
# SLACK_STATE_SECRET=
